### ISSUE TITLE
Display last update date in the extension details page

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/slicer-extensions-webapp#137]
Currently, "Published" date of the extension is displayed in the extension detail page. This is not optimal, because users would need to see what is the actual date/version of the extension that will be installed. Published date can be removed and last update time should be displayed instead and probably version should be displayed, too. 

Code:

https://github.com/KitwareMedical/slicer-extensions-webapp/blob/54bf82d7ebcf6a2b852b0cccc988186a50eec8ae/src/views/ExtensionDetails.vue#L153

`extension.created` should be `extension.updated` and maybe `extension.meta.revision`

Screenshot:

![image](https://github.com/KitwareMedical/slicer-extensions-webapp/assets/307929/05c2429b-04a8-475a-af0f-152737303448)

**Comment by jcfr** [comment]
By update time, do you mean the date of the last commit associated with the extension source tree ?

**Comment by jcfr** [comment]
I just noticed the associated pull request. And yes, since the same "item" may be updated instead of created when no change have been pushed to the extension source tree but a new package  was effectively published.

**Comment by lassoan** [comment]
This issue has come up when investigating SlicerDMRI extension updates for Slicer-5.6.1.

The extension page still shows `December 12, 2023` date, while there was an update on January 10 (see https://github.com/SlicerDMRI/SlicerDMRI/commits/master/).

The extension metadata (https://slicer-packages.kitware.com/api/v1/app/5f4474d0e1d8c75dfc705482/extension?app_revision=32438&arch=amd64&limit=0&os=win) contains:

```
"created": "2023-12-12T12:09:27.681000+00:00",
"updated": "2024-01-11T12:42:31.670000+00:00"
```

So, `updated` field is that we are interested in (that shows when the extension was last updated).

Since packages can be uploaded at any time, it would be nice to also show the `extension.meta.revision` value.

**Comment by lassoan** [comment]
Thank you!
