### ISSUE TITLE
Address "unmet peer dependency" install warnings

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/slicer-extensions-webapp#43]
Output reported while running `yarn install`:

```
warning " > @vue/eslint-config-airbnb@5.3.0" has unmet peer dependency "eslint-plugin-import@^2.18.2".
warning "@vue/eslint-config-airbnb > eslint-import-resolver-webpack@0.13.0" has unmet peer dependency "webpack@>=1.11.0".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "vue-cli-plugin-vuetify > null-loader@3.0.0" has unmet peer dependency "webpack@^4.3.0".
warning " > vuetify-loader@1.7.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "vuetify-loader > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
```

**Comment by jcfr** [comment]
@subdavis  Would you have any guidance to address this warning ?

**Comment by subdavis** [comment]
If you want them to go away, you can `yarn add --peer webpack@^4.0.0`, but it will only make the problem more confusing.  Vue CLI wraps webpack, and its wrapped version is the one that will always be used.  If you end up with a version conflict where, for example, `sass-loader` depends on a version of webpack different than the one embedded in the vue cli dependency, yarn won't be able to tell you about it.

The true expression of dependencies would be "sass-loader has either webpack@version or vue-cli@version as a peer dependency", but it can't, so this is what you get.

I recommend keeping these warnings.

**Comment by gfmoore** [comment]
Well if so, can you put some note into the documentation please as it's a bit worrying to see stuff like this when you're learning!!!
