### ISSUE TITLE
Why are so many thumbnails missing?

### ISSUE THREAD

**Issue by subdavis** [KitwareMedical/slicer-extensions-webapp#9]
Many extensions have a thumbnail URL set that returns 404.  It would be nice if we could drop in a default replacement, but it's harder to detect when the url string is valid (though certainly still possible).

Also, do you have a preference for a default image?  Kitware swoosh?

**Comment by jcfr** [comment]
> do you have a preference for a default image?

https://github.com/Slicer/Slicer/blob/master/Base/QTGUI/Resources/Icons/ExtensionDefaultIcon.png

![](https://raw.githubusercontent.com/Slicer/Slicer/master/Base/QTGUI/Resources/Icons/ExtensionDefaultIcon.png)

> Many extensions have a thumbnail URL set that returns 404

Here is the issue where this is tracked:  https://github.com/Slicer/ExtensionsIndex/issues/1680 

Plan is to update the CI detecting if an URL is invalid: https://github.com/Slicer/ExtensionsIndex/blob/master/scripts/check_description_files.py

**Comment by jcfr** [comment]
Closing. We are currently working on addressing this in https://github.com/Slicer/ExtensionsIndex/pull/1788
